/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "gpio.h"



void init(void){
  
  //enable clock to GPIO A and GPIO B
  ENABLE_GPIOA();
  ENABLE_GPIOB();
  //Pins configuration
  //A1 --> Floating Input
  //A13 --> Floating Input
  //B1 --> (Push-Pull) Output
  //B13 --> (Push-Pull) Output


  //A1 Configuration
  GPIO_config_t pinConfig = {I_FLOATING,PIN1,0};
  GPIO_init(GPIOA,&pinConfig);

  //A13 Configuration
  pinConfig.pinNo = PIN13;
  GPIO_init(GPIOA,&pinConfig);


  //B1 Configuration
  pinConfig.pinNo = PIN1;
  pinConfig.pinMode = O_PUSH_PULL;
  pinConfig.pinSpeed = MAX_10_MHZ;
  GPIO_init(GPIOB,&pinConfig);  

  //B13 Configuration
  pinConfig.pinNo = PIN13;
  GPIO_init(GPIOB,&pinConfig);  

}

void delay(int time){
  for(int i = 0 ; i < time ; i++){
    for(int j = 0 ; j < 255 ; j++);
  }
}

int main(void)
{
  init();
    /* Loop forever */
	for(;;){
    if(GPIO_read_pin(GPIOA,PIN1) == 0){ //single press
      GPIO_toggle_pin(GPIOB,PIN1);
      while(GPIO_read_pin(GPIOA,PIN1) == 0);
    }
    if(GPIO_read_pin(GPIOA,PIN13) == 1){ //multiple press
      GPIO_toggle_pin(GPIOB,PIN13);
    }
    delay(1000);
  }

}
