CC=arm-none-eabi-
CFLAGS= -mcpu=cortex-m4 -gdwarf-2 -g
PROJ =led_toggle_cortexM4
MAP=map_File.map
LIBS=

C_SRC = $(wildcard *.c)
C_OBJ = $(C_SRC:.c=.o) #Turn all .c to .o

S_SRC = $(wildcard *.s)
S_OBJ = $(S_SRC:.s=.o) #Turn all .s to .o

all: $(PROJ).hex

%.o : %.s 
	$(CC)as $(CFLAGS) $< -o $@

%.o : %.c 
	$(CC)gcc $(CFLAGS) -c $< -o $@

$(PROJ).elf: $(C_OBJ) $(S_OBJ)
	$(CC)ld -T linker.ld $(LIBS) $(C_OBJ) $(S_OBJ) -o $@ -Map=$(MAP)
	cp $@ $(PROJ).axf


$(PROJ).hex: $(PROJ).elf
	$(CC)objcopy -O binary $< $@


clean_all:
	rm -rf *.o *.hex *.bin *.elf $(MAP)

