/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../MCAL/usart.h"
#include "../MCAL/gpio.h"


void myHandler(void){
	uint16_t c = UART_receive_data(USART1, NO_POLL);
	UART_send_data(USART1, c, NO_POLL);
}

int main(void)
{
	ENABLE_GPIOA();
	//ENABLE_AFIO();
	GPIO_config_t conf = {PIN9,O_ALT_PUSH_PULL,MAX_10_MHZ};
	GPIO_init(GPIOA, &conf);
	conf.pinNo = PIN10;
	conf.pinMode = I_FLOATING;
	GPIO_init(GPIOA, &conf);
	UART_config_t config = {9600, ASYNC_MODE, NO_PARITY, ONE_STOP, EIGHT_BIT_CHAR, ENABLE_RX_TX, RXNE_ENABLE};
	UART_init(USART1, &config);
	UART_set_callback(myHandler, USART1);
	//conf.pin
    /* Loop forever */
	for(;;){
		//uint16_t c = UART_receive_data(USART1, POLL);
		//UART_send_data(USART1, c, POLL);
	}
}
