/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "LCD.h"
#include "exti.h"

void myCallback(void){
	LCD_send_string("Hello There");

}



int main(void)
{
	ENABLE_GPIOA();
	ENABLE_GPIOB();
	LCD_init();
	EXTI_config_t conf = {EXTI_GPIOB,PIN9,RISING_EDGE,ENABLE,myCallback};
	EXTI_init(&conf);
    /* Loop forever */
	for(;;){


	}
}
